sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bnmCrDGwMGk//ZVxcGJjfIaFWC5L2IT6EnBdkJvY8pz31qXmCnpscnXgm8fPqPjCe/3K5IY20ZeeeOdLLUU5bFEZENVsfY/73G6tr0e4kqjoaNZE037YE0bPddsSogYYhUSjn6hcOdzyELIrJmkqRO4T9fI27K42eCSjFsDMyuNpA2n5IEHtkbUcvRzfhUDYuxn+IzgaBHeIDxpMZMKmmPWjbaJeXF29w86bK2C+zA2YUHynr9m0oIotghi1sqmEhf39bCyjUckPMqCB6uqLyt9GBkMwNDmou2xw4z6PGnwbWBclz1o075uriwZMJ+Li49fG0W3RqC2z6Ck7uxxiJKPTcIA0umsvWfpCETc4guh3Zje1C4lnwNBR0/moa8D/pG2xjEJW9w/8BxYoBK9c6eODuJunLLYsOFrQ19lAJdKX/U4qUGeT4Hzs6HrL8wF1J3iKktVdNUXf5KC7XHRh4BP15q6GMgpWPEfmoNJQhe8kQDae8AjdIHu5hSf6UoqnwPGbqgfUQYOdrF3s58ltdIB6DPE/OhguMgv11wT42q8TdCqnQawdn+GzCQY0zL30KYyFnnr04bd10c9Sy14N1WHdy4PvvDy61gAslSn+dnyjCGZ0bRDf1LBmJK/8kTc5vsrXGQpN4OQSuk+dPrCPqZ17LjkvG9qLC/yQGezTs+c=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Burgomaster-s-Wife---Complete_5583
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy